---
title: "lecture 4"
author: "Jung-Jin Lee"
date: "1/28/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
ht <- read.table(file = "heights.txt", header = T, sep = " ")
dim(ht)
```

```{r}
pnorm(12, mean = 13, sd = 1)
pnorm(13, 13, 1)

1- pnorm(14, mean = 13, sd = 1)
pnorm(14, mean = 13, sd = 1, lower.tail = F)

pnorm(14, mean = 13, sd = 1) - pnorm(11, mean = 13, sd = 1)
```

```{r}
1 - pnorm(15, mean = 13, sd = 1)
pnorm(15, mean = 13, sd = 1, lower.tail = F)

pnorm(-1, mean = 0, sd = 1)
pnorm(-1, 0, 1)
pnorm(-1)
```

```{r}
# guess work
pnorm(1)
pnorm(1.5)
pnorm(1.3)
pnorm(1.27)
qnorm(0.9, mean = 0, sd = 1)

pnorm(1.28152)
qnorm(0.5, mean = 11, sd = 3) 
```

```{r}
# need t_5_0.2
qt(0.8, df = 5)

# need t_4_0.025
qt(1-0.025, df = 4)

# need z_0.025
qnorm(1-0.025)
```

```{r}
mean(iris$Sepal.Width)
sd(iris$Sepal.Width)
```

```{r}
sample1 <- c(12, 13, 13, 14, 13); sample2 <- c(10, 11, 16, 13, 15)

alpha <- 0.05
xbar <- mean(sample1)
sdev <- sd(sample1)
n <- length(sample1)
tval <- qt(1-alpha/2, df = n-1)
CI95 <- xbar + tval*sdev/sqrt(n)*c(-1,1)
```

```{r}
t.test(ht$Mheight)
```

```{r}
st <- starwars
```

```{r}
d <- st %>%
  filter(species == "Human", !is.na(height))
```

```{r}
ggplot(d, aes(gender, height)) +
  geom_boxplot()
```

```{r}
female <- d %>% filter(gender == "female") %>%
  arrange(desc(height))

male <- d %>% filter(gender == "male") 
t.test(male$height)
```



